version: 0.0
os: linux
files: 
  - source: puppet/
    destination: /etc/puppet/codedeploy
  - source: website/
    destination: /var/www/staffly
hooks:
  BeforeInstall:
    - location: scripts/install_puppet.sh
      runas: root
  AfterInstall:
    - location: scripts/apply_puppet.sh
      runas: root
    - location: scripts/deregister_from_elb.sh
      timeout: 400
    - location: scripts/stop_server.sh
      runas: root
      timeout: 120
  ApplicationStart: 
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
    - location: scripts/register_with_elb.sh
      timeout: 120
